#!/bin/bash
#
# get java

java -version
sudo apt-get update
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
java -version

# Add System File Lines
sudo cat <<EOT >> /etc/sysctl.conf
#
# Looker Settings
net.ipv4.tcp_keepalive_time=200
net.ipv4.tcp_keepalive_intvl=200
net.ipv4.tcp_keepalive_probes=5
EOT

sudo cat <<EOT >> /etc/security/limits.conf
#
# Looker Settings
looker     soft     nofile     4096
looker     hard     nofile     4096
EOT

# time synchronization
sudo apt-get install ntp
sudo ntpq -p

# PhantomJS install
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev

sudo apt-get install libfreetype6 libfreetype6-dev
sudo apt-get install libfontconfig1 libfontconfig1-dev

cd ~
export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
sudo tar xvjf $PHANTOM_JS.tar.bz2

sudo mv $PHANTOM_JS /usr/local/share
sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin

phantomjs --version

# create looker user and sudo as them
sudo groupadd looker
sudo useradd -m  -g looker  looker
sudo su - looker
